dotfiles:
  directory: ~/dotfiles
  backup_directory: ~/dotfiles_old
  files:
    - zshrc
    - private
    - Xresources
    - gitignore_global
    - gitconfig
    - profile
    - vimrc
    - shsh
    - vim
    - ideavimrc
    - gvimrc
    - gemrc
    - bash_profile
    - env
    - p10k.zsh
    - finicky.js
    - config

brew:
  packages:
    - name: tmux
      required_version: ">=3.0"
    - name: git
      required_version: ">=2.0.0"
    - name: bash-completion
    - name: ripgrep
    - name: yq

vim:
  plug_url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  plug_install_dir: "~/.vim/autoload/plug.vim"
  plugins_to_install:
    - "plugin1"
    - "plugin2"